In [1]:
import numpy as np

In [2]:
# 1 reshape reshape(2, 3) changes six elements into 2 rows and 3 columns. The number of elements must stay the
# same.
a = np.array([1,2,3,4,5,6])
print(a)
b = a.reshape(2,3)
print(b)

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]


In [3]:
# 2 Size resize() changes the array in place. Unlike reshape(), the total size does not have to remain unchang
a = np.array([1,2,3,4,5,6])
a.resize(3,2)
print(a)

[[1 2]
 [3 4]
 [5 6]]


In [4]:
 # When the new size is larger, NumPy fills extra positions with zeros.

a = np.array([1, 2, 3])
a.resize((2, 3), refcheck=False)
print(a)

[[1 2 3]
 [0 0 0]]


In [5]:
# 3 flatten converts the array to one dimension and returns a copy.
a = np.array([[1,2],[3,4]])
b = a.flatten()
print(b)

[1 2 3 4]


In [6]:
# 4 ravel also creates a 1-D array and tries to return a view when possible.
a = np.array([[1,2],[3,4]])
b = a.ravel()
print(b)

[1 2 3 4]


In [7]:
# 5 transpose For a 2-D array, transpose() swaps rows and columns
a = np.array([[1,2,3],[4,5,6]])
print(a.transpose())

[[1 4]
 [2 5]
 [3 6]]


In [8]:
# 6 T T is a convenient shortcut for transpose() on an ndarray.
a = np.array([[1,2,3],[4,5,6]])
print(a.T)

[[1 4]
 [2 5]
 [3 6]]


In [9]:
# 7 swapaxes Axis 0 and axis 1 are swapped.
a = np.array([[1,2,3],[4,5,6]])
b = np.swapaxes(a,0,1)
print(b)

[[1 4]
 [2 5]
 [3 6]]


In [10]:
# 8 moveaxis moveaxis() moves axis 0 to position 2.
a = np.zeros((2,3,4))
print(a.shape)
b = np.moveaxis(a,0,2)
print(b.shape)

(2, 3, 4)
(3, 4, 2)


In [11]:
# 9 expand_dims  expand_dims() adds a new axis of length 1. axis=0 adds it before the existing axis.
a = np.array([1,2,3])
print(a.shape)
b = np.expand_dims(a,axis=0)
print(b)
print(b.shape)

(3,)
[[1 2 3]]
(1, 3)


In [12]:
# expand_dims() with axis=1 axis=1 inserts the new length-1 axis after the original axis.
a = np.array([1, 2, 3])
b = np.expand_dims(a, axis=1)
print(b)
print(b.shape)

[[1]
 [2]
 [3]]
(3, 1)


In [13]:
# 10 squeeze  removes all axes whose size is 1.
a = np.array([[[1], [2], [3]]])
print(a.shape)
b = np.squeeze(a)
print(b)
print(b.shape)

(1, 3, 1)
[1 2 3]
(3,)


In [14]:
# squeeze() with a chosen axis axis=1 removes only the specified length-1 axis.
a = np.array([[1], [2], [3]])
print(a.shape)
b = np.squeeze(a, axis=1)
print(b)
print(b.shape)

(3, 1)
[1 2 3]
(3,)
