In [1]:
import numpy as np 

In [2]:
# 1 Saving Arrays with np.save
# stores one NumPy array in a .npy file.
arr = np.array([10,20,30,40])
np.save("data.npy",arr)
print("Array Saved Successfully")

Array Saved Successfully


In [3]:
# 2 Loading Arrays with np.load
#  reads a .npy file back into a NumPy array
arr = np.load("data.npy")
print(arr)

[10 20 30 40]


In [4]:
# 3 Saving Multiple Arrays with np.savez
# stores multiple arrays in one .npz file.
a = np.array([1,2,3])
b = np.array([10,20,30])
np.savez("data.npz",numbers=a,values=b)
print("multiple arrays saved")

multiple arrays saved


In [5]:
# 4 . Loading Arrays from np.savez
# Use the names given when saving to access each array.

data = np.load("data.npz")

print(data["numbers"])
print(data["values"])

[1 2 3]
[10 20 30]


In [6]:
# 5 savez_compressed
# stores multiple arrays in a compressed .npz file, usually reducing file size.
arr = np.array([10,20,30,40])
np.savez_compressed("comparessed_data.npz",values=arr)
print("compressed file saved")

compressed file saved


In [7]:
# 6 Writing Text/CSV with np.savetxt
# delimiter=',' means values are separated by commas. fmt='%d' writes integers.
arr = np.array([
 [10, 20, 30],
 [40, 50, 60]
])
np.savetxt("data.csv", arr, delimiter=",", fmt="%d")
print("CSV written")

# Output:
# CSV written
# data.csv contains:
# 10,20,30
# 40,50,60

CSV written


In [8]:
# 7 Reading CSV with np.loadtxt
# reads numeric text/CSV data. By default, numeric values may be loaded as float.
arr = np.loadtxt("data.csv",delimiter=",")
print(arr)

[[10. 20. 30.]
 [40. 50. 60.]]


In [9]:
# Example 
# This combines saving/loading NumPy format and CSV format.
# Create data
marks = np.array([
 [80, 90, 85],
 [70, 75, 80]
])

# Save as NumPy file
np.save("marks.npy", marks)

# Load NumPy file
loaded = np.load("marks.npy")

# Save as CSV
np.savetxt("marks.csv", marks, delimiter=",", fmt="%d")

# Load CSV
csv_data = np.loadtxt("marks.csv", delimiter=",")
print("Original:")
print(marks)
print("Loaded from .npy:")
print(loaded)
print("Loaded from CSV:")
print(csv_data)

Original:
[[80 90 85]
 [70 75 80]]
Loaded from .npy:
[[80 90 85]
 [70 75 80]]
Loaded from CSV:
[[80. 90. 85.]
 [70. 75. 80.]]


In [10]:
# np.save() → save one NumPy array as .npy
# np.load() → load .npy or .npz data
# np.savez() → save multiple arrays in .npz
# np.savez_compressed() → compressed .npz
# np.savetxt() → write text/CSV
# np.loadtxt() → read numeric text/CSV
# np.genfromtxt() → read text/CSV with missing values and more flexible handling
# delimiter → tells NumPy how columns are separated
# header → column names at the top of a CSV/text file
# skiprows → skip rows such as headers
# names=True → use the first row as field names with genfromtxt()
# np.nan → commonly used to represent a missing numeric value