In [1]:
import numpy as np

In [2]:
# 1 Boolean indexing
# Select values using a True/False condition.
arr = np.array([10,20,30,40,50])
result = arr[arr > 25]
print(result)

[30 40 50]


In [3]:
# 2 Boolean arrays
# A comparison creates an array of True and False.
arr = np.array([10,20,30,40,50])
print(arr > 25)

[False False  True  True  True]


In [4]:
# Comparison operators
# Use >, <, >=, <=, ==, and !=.
arr = np.array([10,20,30])
print(arr > 20)

arr1 = np.array([10,20,30])
print(arr1 < 20)

arr2 = np.array([10,20,30])
print(arr2 >= 20)

arr3 = np.array([10,20,30])
print(arr3 <= 20)

arr4 = np.array([10,20,30])
print(arr4 == 20)

arr5 = np.array([10,20,30])
print(arr5 != 20)

[False False  True]
[ True False False]
[False  True  True]
[ True  True False]
[False  True False]
[ True False  True]


In [5]:
# 4 Logical conditions
# Use & for AND and | for OR. Put conditions in parentheses
arr = np.array([10,20,30,40,50])
result = arr[(arr>20) & (arr<50)]
print(result)

arr1 = np.array([10,20,30,40,50])
result1 = arr1[(arr1>20) | (arr1<40)]
print(result1)

[30 40]
[10 20 30 40 50]


In [6]:
# 5 where
# Works like if-else when given condition, true value, and false value.
marks = np.array([35,75,45,90])
result = np.where(marks >= 75,"Pass","Fail")
print(result)

['Fail' 'Pass' 'Fail' 'Pass']


In [7]:
# 6 select 
# Handles multiple conditions.
# when any conditions cant match so excute unknown
marks = np.array([35, 55, 75, 120])
conditions = [
    marks < 40,
    marks < 60,
    marks >= 60
]
choices = ['Fail', 'Average', 'Good']
result = np.select(conditions, choices, default='Unknown')
print(result)

['Fail' 'Average' 'Good' 'Good']


In [8]:
# 7 any
# Returns True if at least one element satisfies the condition.
arr = np.array([10,20,30])
print(np.all(arr > 5))


True


In [9]:
# 8 all 
# Returns True only if every element satisfies the condition.
arr = np.array([10,20,30])
print(np.all(arr > 5))

True


In [10]:
# 9 isin
# Checks whether each value exists in another collection
arr = np.array([10,20,30,40,50])
result = np.isin(arr,[20,40])
print(result)

[False  True False  True False]


In [11]:
# 10 Data Analytics Example 
# Filter Passing students
marks = np.array([35,67,82,45,90])
passed = marks[marks >= 50]
print(passed)

[67 82 90]


In [12]:
# Boolean indexing → filter values
# Boolean array → True/False array
# > <, >=, <=, ==, != → comparisons
# & → AND | | → OR
# np.where() → if-else selection
# np.select() → multiple conditions
# np.any() → at least one True
# np.all() → all True
# np.isin() → membership check