In [1]:
import numpy as np

In [2]:
# 1 Matrix Multiplication using *
A = np.array([[1, 2],
 [3, 4]])
B = np.array([[5, 6],
 [7, 8]])
print(A * B)

# 1×5 = 5, 2×6 = 12, 3×7 = 21, 4×8 = 32.

[[ 5 12]
 [21 32]]


In [3]:
# 2 Matrix Multiplication using @ 
print(A @ B)

# Calculation:
# First value = (1×5) + (2×7) = 5 + 14 = 19
# Second value = (1×6) + (2×8) = 6 + 16 = 22
# Third value = (3×5) + (4×7) = 15 + 28 = 43
# Fourth value = (3×6) + (4×8) = 18 + 32 = 50

[[19 22]
 [43 50]]


In [4]:
# 3 dot For these 2-D matrices, np.dot(A, B) gives the same matrix multiplication result as A @ B.
print(np.dot(A, B))

[[19 22]
 [43 50]]


In [5]:
# 4 matmul  performs matrix multiplication. For normal 2-D matrices, it gives the same result a
print(np.matmul(A, B))

[[19 22]
 [43 50]]


In [6]:
# 5  Quick Difference: *, @, dot(), matmul()
# * = element-wise multiplication
# @ = matrix multiplication
# np.dot = dot product / matrix multiplication depending on dimensions
# np.matmul= matrix multiplication
# For 2-D matrices:
# A @ B == np.dot(A, B) == np.matmul(A, B)

In [7]:
# 6 Dot Product  
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(np.dot(a, b))

# Calculation:
# (1×4) + (2×5) + (3×6)
# = 4 + 10 + 18
# = 32

32


In [8]:
# 7 Inner Product 
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(np.inner(a, b))

# Calculation:
# (1×4) + (2×5) + (3×6) = 32

32


In [9]:
# 8 Outer Product 
a = np.array([1, 2, 3])
b = np.array([4, 5])
print(np.outer(a, b))

# Calculation:
# 1×[4,5] = [4,5]
# 2×[4,5] = [8,10]
# 3×[4,5] = [12,15]

[[ 4  5]
 [ 8 10]
 [12 15]]


In [10]:
# 9 Transpose Rows become columns.
A = np.array([[1, 2, 3],
 [4, 5, 6]])
print(A.T)

[[1 4]
 [2 5]
 [3 6]]


In [11]:
# 10 Inverse 
A = np.array([[1, 2],
 [3, 4]])
print(np.linalg.inv(A))

[[-2.   1. ]
 [ 1.5 -0.5]]


In [12]:
# 11 Determinant 
A = np.array([[1, 2],
 [3, 4]])
print(np.linalg.det(A))

# Calculation for a 2×2 matrix:
# |a b|
# |c d| = (a×d) - (b×c)
# = (1×4) - (2×3)
# = 4 - 6
# = -2

-2.0000000000000004


In [13]:
# 12 Eigenvalues Eigenvalues are special numbers associated with a square matrix.
A = np.array([[1, 2],
 [2, 1]])
values = np.linalg.eigvals(A)
print(values)

[ 3.+0.j -1.+0.j]


In [14]:
# 13 Eigenvalues and Eigenvectors 
A = np.array([[1, 2],
 [2, 1]])
values, vectors = np.linalg.eig(A)
print("Eigenvalues:", values)
print("Eigenvectors:")
print(vectors)

Eigenvalues: [ 3.+0.j -1.+0.j]
Eigenvectors:
[[ 0.70710678+0.j -0.70710678+0.j]
 [ 0.70710678+0.j  0.70710678+0.j]]
