In [1]:
import numpy as np

In [2]:
# 1. sort  np.sort returns a sorted copy of the array. The original array is unchange
a = np.array([5,2,8,1,4])
print(np.sort(a))

[1 2 4 5 8]


In [3]:
# 2 argsort np.argsort() returns the indices that would sort the array. 
a = np.array([50,20,80,10])
idx = np.argsort(a)
print(idx)
print(a[idx])

[3 1 0 2]
[10 20 50 80]


In [4]:
# 3 searchsorted It finds the position where a value should be inserted to keep a sorted array ordered.
a = np.array([10,20,30,40])
print(np.searchsorted(a,25))
print(np.searchsorted(a,30))

2
2


In [5]:
# 4 partition  The element at index 2 is in its final sorted position. Elements before it are smaller/equal and
#   elements after it are larger/equal, but each side is not fully sorted.
a = np.array([9,4,7,1,6,3])
print(np.partition(a,2))

[1 3 4 6 7 9]


In [6]:
# 5 argpartition
a = np.array([9,4,7,1,6,3])
idx = np.argpartition(a,2)
print(idx)
print(a[idx])

[3 5 1 4 2 0]
[1 3 4 6 7 9]


In [7]:
# 6 argmax  np.argmax() returns the index of the largest value
a = np.array([10,50,20,40])
print(np.argmax(a))
print(a[np.argmax(a)])

1
50


In [8]:
# 7 argmin  np.argmin() returns the index of the smallest value.
a = np.array([10,50,20,40])
print(np.argmin(a))
print(a[np.argmin(a)])

0
10


In [9]:
# 8 Sorting Rows axis=1 sorts each row independently.
a = np.array([
    [30,10,20],
    [60,40,50]
])
print(np.sort(a,axis=1))

[[10 20 30]
 [40 50 60]]


In [10]:
# 9 Sorting columns axis=0 sorts each column independently
a = np.array([
    [30,60,20],
    [10,40,50]
])
print(np.sort(a,axis=0))

[[10 40 20]
 [30 60 50]]


In [11]:
# 10 Descending sorting  NumPy sorts ascending by default. [::-1] reverses the sorted array to get descending order.
a = np.array([5,2,8,1,4])
desc = np.sort(a)[::-1]
print(desc)

[8 5 4 2 1]


In [12]:
# np.sort(a) -> sorted values
# np.argsort(a) -> sorting indices
# np.searchsorted(a, x) -> insertion position
# np.partition(a, k) -> partial sorting around index k
# np.argpartition(a, k) -> indices for partial sorting
# np.argmax(a) -> index of maximum
# np.argmin(a) -> index of minimum
# np.sort(a, axis=1) -> sort rows
# np.sort(a, axis=0) -> sort columns
# np.sort(a)[::-1] -> descending order
# Important: axis=0 works down the columns; axis=1 works across the rows.