In [1]:
import numpy as np 

In [2]:
# 1 Setup
data = np.array([10,20,30,40,50])
print(data)

[10 20 30 40 50]


In [3]:
# 2 mean
# Finds the arithmetic average.
data = np.array([10,20,30,40,50])
result = np.mean(data)
print(result)

30.0


In [4]:
# 3 median
# Finds the middle value after sorting the data.
data = np.array([10,20,30,40,50])
result = np.median(data)
print(result)

30.0


In [5]:
# 4 average
# Calculates an average. It can also calculate a weighted average.
data = np.array([10,20,30,40,50])
result = np.average(data)
print(result)

30.0


In [6]:
# 5 average() with weights
# Useful when some values have more importance than others.
marks = np.array([60,70,80])
weights = np.array([1,2,3])
result = np.average(marks, weights=weights)
print(result)

# (60 × 1) + (70 × 2) + (80 × 3)
# --------------------------------
#        1 + 2 + 3

# 60 × 1 = 60
# 70 × 2 = 140
# 80 × 3 = 240

# 60 + 140 + 240 = 440

# 1 + 2 + 3 = 6

# 440 / 6
# = 73.33333333333333

73.33333333333333


In [7]:
# 6 std
# Finds standard deviation, which measures how spread out values are.
data = np.array([10,20,30,40,50])
result = np.std(data)
print(result)

# Data = [10, 20, 30, 40, 50]

# Mean = 30

# SD = √[((10-30)² + (20-30)² + (30-30)² + (40-30)² + (50-30)²) / 5]

#    = √[(400 + 100 + 0 + 100 + 400) / 5]

#    = √[1000 / 5]

#    = √200

#    = 14.142135623730951

14.142135623730951


In [8]:
# 7 var
# Finds variance, another measure of spread.
data = np.array([10,20,30,40,50])
result = np.var(data)
print(result)

# Mean = (10 + 20 + 30 + 40 + 50) / 5
#      = 150 / 5
#      = 30

# Variance = [(10-30)² + (20-30)² + (30-30)² + (40-30)² + (50-30)²] / 5

#          = [(-20)² + (-10)² + 0² + 10² + 20²] / 5

#          = [400 + 100 + 0 + 100 + 400] / 5

#          = 1000 / 5

#          = 200

200.0


In [9]:
# 8 min
# Finds the smallest value.
data = np.array([10,20,30,40,50])
result = np.min(data)
print(result)

10


In [10]:
# 9 Max
# Finds the largest value.
data =np.array([10,20,30,40,50])
result = np.max(data)
print(result)

50


In [11]:
# 10 ptp
# Range
# Finds the range: maximum value minus minimum value.
data = np.array([10,20,30,40,50])
result = np.ptp(data)
print(result)

40


In [12]:
# 11 percentile
# Finds a value below which a given percentage of observations falls.
# Percentile → use 0 to 100
# Quantile → use 0 to 1
data = np.array([10,20,30,40,50])
result = np.percentile(data, 50)
print(result)

30.0


In [13]:
# 12 quantile
# Similar to percentile, but the input is written as a fraction from 0 to 1.
# Percentile → use 0 to 100
# Quantile → use 0 to 1
data = np.array([10,20,30,40,50])
result = np.quantile(data, 0.5)
print(result)

30.0


In [14]:
# 13 argmax
# Returns the index position of the largest value.
data = np.array([10,20,30,40,50])
result = np.argmax(data)
print(result)

4


In [15]:
# 14 argmin
# Returns the index position of the smallest value.
data = np.array([10,20,30,40,50])
result = np.argmin(data)
print(result)

0


axis = 0
axis = 1

In [16]:
arr = np.array([
    [10,20,30],
    [40,50,60]
])
print(arr)

[[10 20 30]
 [40 50 60]]


In [17]:
# 16 Mean by row — axis=1
result = np.mean(arr, axis=1)
print(result)

[20. 50.]


In [18]:
# 17  Mean by column — axis=0
result = np.mean(arr, axis=0)
print(result)

[25. 35. 45.]


In [19]:
# 18  Sum by row — axis=1
result = np.sum(arr, axis=1)
print(result)

[ 60 150]


In [20]:
# 19. Sum by column — axis=0
result = np.sum(arr, axis=0)
print(result)

[50 70 90]


In [21]:
# 20. Standard deviation by row — axis=1
result = np.std(arr, axis=1)
print(result)

# Row 1: [10, 20, 30]
# Mean = 20
# SD = √[((10-20)² + (20-20)² + (30-20)²) / 3]
#    = √[(100 + 0 + 100) / 3]
#    = √66.67
#    = 8.1649

# Row 2: [40, 50, 60]
# Mean = 50
# SD = √[((40-50)² + (50-50)² + (60-50)²) / 3]
#    = √[(100 + 0 + 100) / 3]
#    = 8.1649

[8.16496581 8.16496581]


In [22]:
# 21. Standard deviation by column — axis=0
result = np.std(arr, axis=0)
print(result)

# Column 1: [10, 40]
# Mean = 25
# SD = √[((10-25)² + (40-25)²) / 2]
#    = √[(225 + 225) / 2]
#    = √225
#    = 15

# Mean = 35
# SD = √[((20-35)²+(50-35)²)/2]
#    = √225 = 15

# Mean = 45
# SD = √[((30-45)²+(60-45)²)/2]
#    = √225 = 15

[15. 15. 15.]


In [23]:
# 22. Variance by row — axis=1
result = np.var(arr, axis=1)
print(result)

# Mean = (10+20+30)/3 = 20
# Variance = [(10-20)²+(20-20)²+(30-20)²]/3
#           = (100+0+100)/3
#           = 66.67

# Mean = (40+50+60)/3 = 50
# Variance = [(40-50)²+(50-50)²+(60-50)²]/3
#           = (100+0+100)/3
#           = 66.67

[66.66666667 66.66666667]


In [24]:
# 23. Variance by column — axis=0
result = np.var(arr, axis=0)
print(result)

# Mean = (10+40)/2 = 25
# Variance = [(10-25)² + (40-25)²]/2
#           = (225+225)/2
#           = 225

# Mean = 35
# Variance = [(20-35)² + (50-35)²]/2
#           = 225

# Mean = 45
# Variance = [(30-45)² + (60-45)²]/2
#           = 225

[225. 225. 225.]


In [25]:
# Function Purpose
# np.mean() Average
# np.median() Middle value
# np.average() Average / weighted average
# np.std() Standard deviation
# np.var() Variance
# np.min() Smallest value
# np.max() Largest value
# np.ptp() Maximum − minimum
# np.percentile() Percentile value
# np.quantile() Quantile value
# np.argmax() Index of maximum
# np.argmin() Index of minimum
# axis=0 Calculate down rows → one result per column
# axis=1 Calculate across columns → one result per row