In [1]:
import numpy as np

In [2]:
arr = np.array([[10,20,30],
               [40,50,60]])
arr

array([[10, 20, 30],
       [40, 50, 60]])

In [3]:
arra = np.array([[[10,20,30],
                 [40,50,60],
                 [70,80,90]]])
arra

array([[[10, 20, 30],
        [40, 50, 60],
        [70, 80, 90]]])

In [4]:
# 1 ndim — Number of Dimensions
print(arr.ndim)
print(arra.ndim)

2
3


In [5]:
# 2 shape — Size of Each Dimension
print(arr.shape) 
print(arra.shape) 

(2, 3)
(1, 3, 3)


In [6]:
# 3 size — Total Number of Elements
print(arr.size)
print(arra.size)

6
9


In [7]:
# 4 dtype — Data Type of Elements
print(arr.dtype)
print(arra.dtype)

int64
int64


In [8]:
# 5 itemsize — Bytes Used by One Element
print(arr.itemsize)

8


In [9]:
# 6 nbytes — Total Bytes Used by Array Data
print(arr.nbytes)
print(arra.nbytes)

48
72


In [10]:
# 7 T — Transpose of the Array
print(arr.T)
print(arra.T)

[[10 40]
 [20 50]
 [30 60]]
[[[10]
  [40]
  [70]]

 [[20]
  [50]
  [80]]

 [[30]
  [60]
  [90]]]


In [11]:
# 8  flags — Information About the Array
print(arr.flags)
print(arra.flags)

  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False

  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False



In [12]:
# ndim → Number of dimensions
# shape → Rows and columns / size of each dimension
# size → Total number of elements
# dtype → Data type of elements
# itemsize → Bytes used by one element
# nbytes → Total bytes used by array data
# T → Transpose
# flags → Array storage/access information