In [2]:
import numpy as np

In [3]:
arr = np.array([[10,20,30],
                [40,50,60],
                [70,80,90]])
arr

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [4]:
# 1 Row Selection
print(arr[1])

[40 50 60]


In [5]:
# 2 Column Selection
print(arr[:,1])

[20 50 80]


In [6]:
# 3 Specifi Element
print(arr[1,2])

60


In [7]:
# 4 Multiple Rows
print(arr[[0,2]])

[[10 20 30]
 [70 80 90]]


In [8]:
# 5 Multiple Rows
print(arr[:,[0,2]])

[[10 30]
 [40 60]
 [70 90]]


In [9]:
# 6 Row Slicing
print(arr[0:2, :])

[[10 20 30]
 [40 50 60]]


In [10]:
# 7 Column Slicing
print(arr[:,0:2])

[[10 20]
 [40 50]
 [70 80]]


In [ ]:
# 