In [1]:
import numpy as np

In [2]:
arr = np.array([[[1,2,3], [4,5,6]],
                [[7,8,9], [10,11,12]]])
arr

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [3]:
# 1 Accessing Dimensions
print(arr.ndim)
print(arr.shape)

3
(2, 2, 3)


In [4]:
# 2 Selecting Layers
print(arr[0])

[[1 2 3]
 [4 5 6]]


In [5]:
# 3 Selecting Rows
print(arr[:,1,:])

[[ 4  5  6]
 [10 11 12]]


In [6]:
# 4 Selecting Columns
print(arr[:,:,2])

[[ 3  6]
 [ 9 12]]


In [7]:
# 5 Advanced Slicing
print(arr[:,0:2,1:3])

[[[ 2  3]
  [ 5  6]]

 [[ 8  9]
  [11 12]]]
