In [1]:
import numpy as np 

In [2]:
# 1 np.random is NumPy's module for random-number generation.
print(np.random.rand())

0.09168252002599997


In [3]:
# 2 Generates random floats from 0 (inclusive) to 1 (exclusive).
arr = np.random.rand(3)
print(arr)

[0.03593968 0.06360102 0.6805891 ]


In [4]:
# For 2 rows and 3 columns
arr2 = np.random.rand(2,3)
print(arr2)

[[0.5266246  0.82836498 0.61963311]
 [0.33318935 0.83448989 0.04246028]]


In [5]:
# 3 Generates values from the standard normal distribution (mean 0, standard deviation 1).
arr = np.random.randn(5)
print(arr)

[-0.57599408 -1.72374812 -2.79910895 -1.55614566 -0.58580543]


In [6]:
# 4 Generates random integers; the upper limit is excluded.
arr = np.random.randint(1,10,6)
print(arr)

[4 8 9 4 4 3]


In [7]:
# 5 Generates random floats from 0 (inclusive) to 1 (exclusive).
arr = np.random.random(4)
print(arr)

[0.30084605 0.06282642 0.73221189 0.49688616]


In [8]:
# 6 Generates random floating-point values in a chosen range.
arr = np.random.uniform(10,20,5)
print(arr)

[16.70269374 13.02869744 10.516892   19.08796495 19.83688276]


In [9]:
# 7 Generates values from a normal distribution. The arguments are mean, standard deviation, and size.
# 50 = mean, 10 = standard deviation, 5 = number of values.
arr = np.random.normal(50,10,5)
print(arr)

[55.35766136 66.72801346 46.90320507 33.32146039 53.41189212]


In [10]:
# 8 Randomly selects values from a sequence.
arr = np.array([10,20,30,40])
x = np.random.choice(arr)
print(x)

# For 2 Values Selections 
np.random.choice(arr,2)

40


array([10, 40])

In [11]:
# 9 Shuffles the original array in place.
arr = np.array([1,2,3,4,5])
np.random.shuffle(arr)
print(arr)

[4 5 3 1 2]


In [12]:
# 10 Returns a shuffled permutation without changing the original array.
arr = np.array([1,2,3,4,5])
new_arr = np.random.permutation(arr)
print(new_arr)
print(arr)

[2 3 5 1 4]
[1 2 3 4 5]


In [13]:
# 11 Sets the starting state of NumPy's legacy global random generator, making repeated runs reproducible.
np.random.seed(10)
print(np.random.randint(1,10,5))

[5 1 2 1 2]


In [14]:
# 12 Creates the modern NumPy random-number Generator.
rng = np.random.default_rng()
print(rng.random(5))

[0.94811923 0.22764872 0.84547713 0.92777486 0.54132556]


In [15]:
# 13 The object returned by default_rng() is a Generator. Its methods create random values.
rng = np.random.default_rng()
print(rng.integers(1,10,5))

[4 4 3 9 8]


In [16]:
# 14 Use the same seed with default_rng() to reproduce a sequence.
rng1 = np.random.default_rng(42)
print(rng1.integers(1,100,5))

rng2 = np.random.default_rng(42)
print(rng2.integers(1,100,5))

[ 9 77 65 44 43]
[ 9 77 65 44 43]


In [17]:
# rand() → floats 0 to 1
# randn() → standard normal values
# randint() → random integers
# random() → floats 0 to 1
# uniform() → floats in a range
# normal() → normal distribution
# choice() → random selection
# shuffle() → changes original array
# permutation() → returns shuffled permutation
# seed() → reproducibility for legacy global RNG
# default_rng() → modern Generator