In [1]:
import numpy as np 

In [2]:
# 1. What is a ufunc?
# A ufunc means Universal Function. It performs operations efficiently on NumPy array elements.
arr = np.array([1,4,9])
print(np.sqrt(arr))

[1. 2. 3.]


In [3]:
# 2. Element-wise operations
# The operation is performed separately on each element
arr = np.array([1,4,9,16])
print(np.sqrt(arr))

[1. 2. 3. 4.]


In [4]:
# 3. Unary ufunc
# A unary ufunc takes one input
arr = np.array([1,4,9])
result = np.sqrt(arr)
print(result)

[1. 2. 3.]


In [5]:
# 4. Binary ufunc
# A binary ufunc works with two inputs.
a = np.array([10,20,30])
b = np.array([1,2,3])
print(np.add(a,b))

[11 22 33]


In [6]:
# 5. np.sqrt()
# Square root of each element.
a = np.array([4,9,16,25])
print(np.sqrt(a))

[2. 3. 4. 5.]


In [7]:
# 6. np.exp()
# Calculates e raised to each value.
a = np.array([0,1,2])
print(np.exp(a))

[1.         2.71828183 7.3890561 ]


In [8]:
# 7. np.log()
# Natural logarithm, base e
a = np.array([1,np.e,np.e ** 2])
print(np.log(a))

[0. 1. 2.]


In [9]:
# 8 np.log10
# Base - 10 Logarithm
a = np.array([1,10,100,1000])
print(np.log10(a))

[0. 1. 2. 3.]


In [10]:
# 8.1 np.log2
# Base - 2 Logarithm
a = np.array([1,10,100,1000])
print(np.log2(a))

[0.         3.32192809 6.64385619 9.96578428]


In [11]:
# 9. np.sin()
# Sine of angles in radians.
a = np.array([0,np.pi / 2,np.pi])
print(np.sin(a))

[0.0000000e+00 1.0000000e+00 1.2246468e-16]


In [12]:
# 10. np.cos()
# Cosine of angles in radians. 
a = np.array([0,np.pi / 2,np.pi])
print(np.cos(a))

[ 1.000000e+00  6.123234e-17 -1.000000e+00]


In [13]:
# 11. np.tan()
# Tangent of angles in radians.
a = np.array([0,np.pi / 4])
print(np.tan(a))

[0. 1.]


In [14]:
# 12. np.floor()
# Rounds down to the nearest integer.
a = np.array([1.2,2.9,-1.2])
print(np.floor(a))

[ 1.  2. -2.]


In [15]:
# 13. np.ceil()
# Rounds up to the nearest integer.
a = np.array([1.2,2.1,-1.2])
print(np.ceil(a))

[ 2.  3. -1.]


In [16]:
# 14. np.round()
# Rounds to a chosen number of decimal places.
a = np.array([1.234,2.567,3.891])
print(np.round(a,2))

[1.23 2.57 3.89]


In [17]:
# 15. np.trunc()
# Removes the fractional part by moving toward zero
a = np.array([1.9,2.7,-1.9,-2.7])
print(np.trunc(a))

[ 1.  2. -1. -2.]


In [18]:
# 16. np.absolute()
# Returns absolute values; equivalent to np.abs()
a = np.array([-10,-5,0,5,10])
print(np.absolute(a))

[10  5  0  5 10]


In [ ]:
# unction	Meaning	Example
# np.sqrt()	Square root	        np.sqrt([4, 9]) → [2, 3]
# np.exp()	Exponential	        np.exp([1, 2])
# np.log()	Natural logarithm	np.log([1, 10])
# np.log10()  Base-10 logarithm	np.log10([10, 100])
# np.sin()	Sine	            np.sin(a)
# np.cos()	Cosine	            np.cos(a)
# np.floor() Round down	        np.floor([1.2, 2.9]) → [1, 2]
# np.ceil()	Round up	        np.ceil([1.2, 2.1]) → [2, 3]
# np.abs()	Absolute value	    np.abs([-5, 3]) → [5, 3]