In [1]:
import numpy as np

In [2]:
# 1 Matrix Basic A matrix is a rectangular arrangement of numbers in rows and columns
a = np.array([[1,2],
              [3,4]])

print(a)

[[1 2]
 [3 4]]


In [3]:
# 2 Matrix Creation Create a matrix using np.array().
a = np.array([[10,20,30],
              [40,50,60]])

print(a)
print("shape:",a.shape)

[[10 20 30]
 [40 50 60]]
shape: (2, 3)


In [4]:
# 3 Matrix Addition Add corresponding elements of two matrices.
a = np.array([[1,2],
              [3,4]])

b = np.array([[5,6],
              [7,8]])

print(a + b)

[[ 6  8]
 [10 12]]


In [5]:
# 4 Matrix Subtraction Subtract corresponding elements.
A = np.array([[10, 20],
              [30, 40]])

B = np.array([[1, 2],
              [3, 4]])

print(A - B)

[[ 9 18]
 [27 36]]


In [7]:
# 5 Matrix Multiplication Matrix multiplication uses rows of the first matrix and columns of the second matrix.
A = np.array([[1, 2],
              [3, 4]])
B = np.array([[5, 6],
              [7, 8]])
print(A @ B)

# (1×5)+(2×7)
# =5+14=
# 19
# 	​
# (1×6)+(2×8)
# =6+16=
# 22

# (3×5)+(4×7)
# =15+28=
# 43
# 	​
# (3×6)+(4×8)
# =18+32=
# 50
	​


[[19 22]
 [43 50]]


In [8]:
# 6 Element-wise Multiplication Multiply elements at the same positions.
A = np.array([[1, 2],
              [3, 4]])
B = np.array([[5, 6],
              [7, 8]])
print(A * B)

[[ 5 12]
 [21 32]]


In [9]:
# 7 Transpose Transpose changes rows into columns.
a = np.array([[1,2,3],
              [4,5,6]])

print(a.T)

[[1 4]
 [2 5]
 [3 6]]


In [10]:
# 8  Identity Matrix An identity matrix has 1s on the main diagonal and 0s elsewhere.
I = np.eye(3)

print(I)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [12]:
# 9 Diagonal Matrix A diagonal matrix has values on the main diagonal and zeros elsewhere.
D = np.diag([10,20,30])

print(D)

[[10  0  0]
 [ 0 20  0]
 [ 0  0 30]]


In [13]:
# 10  np.dot np.dot() performs a dot product. For 2-D matrices, it can perform matrix multiplication.
a = np.array([[1,2],
              [3,4]])

b = np.array([[5,6],
              [7,8]])

print(np.dot(a,b))

[[19 22]
 [43 50]]


In [14]:
# 11 matmul performs matrix multiplication. 
a = np.array([[1,2],
              [3,4]])

b = np.array([[5,6],
              [7,8]])

print(np.matmul(a,b))

[[19 22]
 [43 50]]


In [15]:
# 12 linalg.det Finds the determinant of a square matrix.
a = np.array([[1,2],
              [3,4]])

print(np.linalg.det(a))

# (1×4)−(2×3)
# 1×4=4
# 2×3=6

# 4−6=−2

-2.0000000000000004


In [16]:
# 13 linalg.inv Finds the inverse of an invertible square matrix.
a = np.array([[1,2],
              [3,4]])

print(np.linalg.inv(a))

[[-2.   1. ]
 [ 1.5 -0.5]]


In [17]:
# 14 linalg.solve Solves a system of linear equations. Here: x + y = 5 and 2x + 3y = 13.
a = np.array([[1,1],
              [2,3]])

b = np.array([5,13])

x = np.linalg.solve(a,b)
print(x)

[2. 3.]


In [18]:
# 15 inalg.eig Finds eigenvalues and eigenvectors
A = np.array([[2, 0],
 [0, 3]])
values, vectors = np.linalg.eig(A)
print("Eigenvalues:", values)
print("Eigenvectors:")
print(vectors)

Eigenvalues: [2.+0.j 3.+0.j]
Eigenvectors:
[[1.+0.j 0.+0.j]
 [0.+0.j 1.+0.j]]


In [19]:
# 16 linalg.eigvals Finds only the eigenvalues.
A = np.array([[2, 0],
 [0, 3]])
print(np.linalg.eigvals(A))

[2.+0.j 3.+0.j]


In [20]:
# 17 linalg.svd SVD means Singular Value Decomposition. It decomposes a matrix into U, singular values, and Vt.
A = np.array([[1, 0],
 [0, 2]])
U, S, Vt = np.linalg.svd(A)

print("U:")
print(U)
print("Singular values:")
print(S)
print("Vt:")
print(Vt)

U:
[[0. 1.]
 [1. 0.]]
Singular values:
[2. 1.]
Vt:
[[0. 1.]
 [1. 0.]]
