In [1]:
import numpy as np

In [2]:
# 1 Integer
arr = np.array([10,20,30], dtype=np.int32)
print(arr)
print(arr.dtype)

[10 20 30]
int32


In [3]:
# 2 Unsigned integer
arr = np.array([0,10,20], dtype=np.uint8)
print(arr)
print(arr.dtype)

[ 0 10 20]
uint8


In [4]:
# 3 Float
arr = np.array([10.5,20.2,30.7], dtype=np.float64)
print(arr)
print(arr.dtype)

[10.5 20.2 30.7]
float64


In [5]:
# 4 Complex
arr = np.array([2+3j, 4+5j])
print(arr)

[2.+3.j 4.+5.j]


In [6]:
# 5 Boolean
arr = np.array([True,False,True])
print(arr)
print(arr.dtype)

[ True False  True]
bool


In [7]:
# 6 String 
arr = np.array(["Apple","Mango","Banana"])
print(arr)

['Apple' 'Mango' 'Banana']


In [8]:
# 7 Unicode
arr = np.array(["hello","jenish"])
print(arr)

['hello' 'jenish']


In [9]:
# 8 Object
arr = np.array([10,"Hello",3.5], dtype=object)
print(arr)

[10 'Hello' 3.5]


In [10]:
# 9 Checking dtype
arr = np.array([10,20,30])
print(arr.dtype)

int64


In [11]:
# 10 Changing dtype
arr = np.array([10,20,30])
new_arr = arr.astype(np.float32)
print(new_arr)

[10. 20. 30.]


In [12]:
# 11 astype
arr = np.array([10,20,30])
new_arr = arr.astype(np.float32)
print(new_arr)
print(new_arr.dtype)

[10. 20. 30.]
float32


In [13]:
# 12 Type Conversion
arr = np.array([1,2,3])
arr_float = arr.astype(float)
print(arr_float)

[1. 2. 3.]


In [14]:
# 13 Memory Optimization
arr = np.array([10,20,30],dtype=np.int64)
small_arr = arr.astype(np.int32)
print(arr.nbytes)
print(small_arr.nbytes)

24
12


In [15]:
# Quick Revision
# int → whole numbers
# uint → non-negative whole numbers
# float → decimal numbers
# complex → real + imaginary numbers
# bool → True / False
# string / Unicode → text
# object → Python objects
# dtype → checks data type
# astype() → converts data type
# nbytes → checks memory used by array