In [1]:
import numpy as np 

In [2]:
# 1 Fancy Inddexing 
# Fancy indexing lets you select multiple positions at once using an array/list of indexes. Here indexes 0, 2, and 4
# select 10, 30, and 50

arr = np.array([10,20,30,40,50])
result = arr[[0,2,4]]
print(result)

[10 30 50]


In [3]:
# 2 Boolean Indexing 
# Boolean indexing selects values where a condition is True. Only 55 and 70 are greater than 40.
arr = np.array([10,25,40,55,70])
result = arr[arr > 40]
print(result)

[55 70]


In [4]:
# 3 Integer Array Indexing
# Integer array indexing uses integer positions stored in an array. Positions 1, 3, and 4 return 20, 40, and 50
arr = np.array([10,20,30,40,50])
indexes = np.array([1,3,4])
result = arr[indexes]
print(result)

[20 40 50]


In [5]:
# 4 Advanced Slicing 
# The slice starts at index 2, stops before index 9, and takes every 2nd element
arr = np.arange(1, 11)
result = arr[2:9:2]
print(result)

[3 5 7 9]


In [6]:
# 5 Combining Indexing 
# First arr[1:4] gives [20 30 40]. Then indexes 0 and 2 select 20 and 40 from that temporary result
arr = np.array([10,20,30,40,50])
result = arr[1:4][[0,2]]
print(result)

[20 40]


In [7]:
# 6  Indexing with Multiple Dimensions
# NumPy pairs the indexes element-by-element: (row 0, column 1) gives 20, and (row 2, column 2) gives 90.
arr = np.array([
    [10,20,30],
    [40,50,60],
    [70,80,90]
])
result = arr[[0,2],[1,2]]
print(result)

[20 90]


In [8]:
# 7 ix 
#  creates an open mesh of row and column indexes, so every selected row is combined with every selected
#  column.
arr = np.array([
    [10,20,30],
    [40,50,60],
    [70,80,90]
])

rows = [0,2]
cols = [1,2]
result = arr[np.ix_(rows,cols)]
print(result)

[[20 30]
 [80 90]]


In [9]:
# 8 take 
#  returns elements from specified indexes. It is useful when indexes are stored separately
arr = np.array([10,20,30,40,50])
result = np.take(arr,[0,2,4])
print(result)

[10 30 50]


In [10]:
# 9 put 
# changes values at selected indexes. Index 1 becomes 200 and index 3 becomes 400.
arr = np.array([10,20,30,40,50])
np.put(arr,[1,3],[200,400])
print(arr)

[ 10 200  30 400  50]


In [11]:
# 10 take_along_axis
# take_along_axis() takes values using indexes along a chosen axis. With axis=1, indexes select columns
# separately for each row.
arr = np.array([
    [10,30,20],
    [60,40,50]
])
indexes = np.array([
    [2,0],
    [1,2]
])

result = np.take_along_axis(arr,indexes,axis=1)
print(result)

[[20 10]
 [40 50]]
