In [1]:
import numpy as np 

In [2]:
# 1 Sum
arr = np.array([10,20,30,40,50])
print(np.sum(arr))

150


In [3]:
# 2 prod
# 2 x 3 x 4
arr = np.array([2,3,4])
print(np.prod(arr))

24


In [4]:
# 3 cumsum
# 1st: 10
# 2nd: 10 × 20 = 200
# 3rd: 200 × 30 = 6000
# 4th: 6000 × 40 = 240000
# 5th: 240000 × 50 = 12000000

arr = np.array([10,20,30,40,50])
print(np.cumprod(arr))

[      10      200     6000   240000 12000000]


In [5]:
# 4 cumprod
# 2 x 2 x 6
arr = np.array([2,3,4])
print(np.cumprod(arr))

[ 2  6 24]


In [6]:
# 5 min
arr = np.array([10,5,30,2,20])
print(np.min(arr))

2


In [7]:
# 6 Max
arr = np.array([10,5,30,2,20])
print(np.max(arr))

30


In [8]:
# 7 Mean
arr = np.array([10,20,30,40])
print(np.mean(arr))

25.0


In [9]:
# 8 median
arr = np.array([10,20,30,40,50])
print(np.median(arr))

30.0


In [10]:
# 9 std
arr = np.array([10,20,30,40])
print(np.std(arr))

11.180339887498949


In [11]:
# 10 var
# Calculates variance (standard deviation squared).
arr = np.array([10,20,30,40])
print(np.var(arr))

125.0


In [12]:
# 11 ptp
# Returns range = maximum minus minimum.
# 40-10 = 30
arr = np.array([10,20,30,40])
print(np.ptp(arr))

30


In [13]:
# 12 axis = 0
# For a 2D array, axis=0 works down rows and gives one result per column.
arr = np.array([[10,20,30],[40,50,60]])
print(np.sum(arr,axis=0))

[50 70 90]


In [14]:
# 13 axis = 1
# For a 2D array, axis=1 works across columns and gives one result per row.
arr = np.array([[10,20,30],[40,50,60]])
print(np.sum(arr,axis=1))

[ 60 150]


In [15]:
# 14 keepdims = true
# Keeps the reduced dimension
arr = np.array([[10,20,30],[40,50,60]])
result = np.sum(arr,axis=1,keepdims=True)
print(result)

[[ 60]
 [150]]


In [16]:
# 15 zxis = 0 + keepdims = true
# Keeps a 2D result while calculating column-wise.
arr = np.array([[1,2,3],[4,5,6]])
print(np.mean(arr,axis=0,keepdims=True))

[[2.5 3.5 4.5]]
