In [1]:
import numpy as np

Basic Arithmetic

In [2]:
# 1 Addition
a = np.array([10,20,30,40,50])
b = np.array([60,70,80,90,100])
print(a + b)

[ 70  90 110 130 150]


In [3]:
# 2 Subtraction
a = np.array([10,20,30,40,50])
b = np.array([60,70,80,90,100])
print(a - b)

[-50 -50 -50 -50 -50]


In [4]:
# 3 Divison
a = np.array([10,20,30,40,50])
b = np.array([60,70,80,90,100])
print(a / b)

[0.16666667 0.28571429 0.375      0.44444444 0.5       ]


In [5]:
# 4 Multiplication
a = np.array([10,20,30,40,50])
b = np.array([60,70,80,90,100])
print(a * b)

[ 600 1400 2400 3600 5000]


In [6]:
# 5 Modulus
a = np.array([10,21,32])
b = np.array([3,4,5])
print(a % b)

[1 1 2]


In [7]:
# 6 Power 
a = np.array([1,2,3,4,5])
print(a ** 2)

[ 1  4  9 16 25]


In [8]:
# 7 Floor Division
a = np.array([152,204,312,441,510])
b = np.array([10,20,30,40,50])
print(a // b)

[15 10 10 11 10]


Numpy Functions

In [9]:
# 1 NumPy function for element-wise addition
print(np.add(a,b))

[162 224 342 481 560]


In [10]:
# 2 NumPy function for element-wise subtraction.
print(np.subtract(a,b))

[142 184 282 401 460]


In [11]:
# 3 NumPy function for element-wise multiplication
print(np.multiply(a,b))

[ 1520  4080  9360 17640 25500]


In [12]:
# 4 NumPy function for element-wise division
print(np.divide(a,b))

[15.2   10.2   10.4   11.025 10.2  ]


In [13]:
# 5 NumPy function for element-wise remainder
print(np.mod(a,b))

[ 2  4 12  1 10]


In [14]:
# 6 Raises each element to a power.
a = np.array([2,3,4])
print(np.power(a,2))

[ 4  9 16]


In [15]:
# 7 Finds the square root.
a = np.array([4,9,16,25])
print(np.sqrt(a))

[2. 3. 4. 5.]


In [16]:
# 8 Finds the square of each value
a = np.array([4,9,16,25])
print(np.square(a))

[ 16  81 256 625]


In [17]:
# 9 Returns absolute values, removing negative signs
a = np.array([-10,-5,0,5,10])
print(np.abs(a))

[10  5  0  5 10]


In [18]:
# 10 Returns -1 for negative, 0 for zero, and 1 for positive.
a = np.array([-10,0,25])
print(np.sign(a))

[-1  0  1]
