In [1]:
import numpy as np
# view() = shared data 
# copy() = independent data

In [2]:
# 1  What is a View
# A view is a new array object that looks at the same underlying data as the original array.
arr = np.array([10,20,30,40])
view_arr = arr.view()

view_arr[0] = 999

print("Original:",arr)
print("View:",view_arr)

Original: [999  20  30  40]
View: [999  20  30  40]


In [3]:
# 2 What is a Copy
# A copy creates a completely separate array with its own data.
arr = np.array([10,20,30,40])
copy_arr = arr.copy()

copy_arr[0] = 999

print("Original:",arr)
print("Copy:",copy_arr)

Original: [10 20 30 40]
Copy: [999  20  30  40]


In [4]:
# 3 Shallow Copy
# For NumPy arrays, the important practical distinction is usually between a view and an independ
arr = np.array([1,2,3])
view_arr = arr.view()

view_arr[1] = 200

print(arr)
print(view_arr)

[  1 200   3]
[  1 200   3]


In [5]:
# 4 Deep copy 
# An independent NumPy copy is made with copy().
arr = np.array([10,20,30])
deep_copy = arr.copy()

deep_copy[2] = 500

print(arr)
print(deep_copy)

[10 20 30]
[ 10  20 500]


In [6]:
# 5 copy() creates an independent array.
arr = np.array([10, 20, 30])
new_arr = arr.copy()

new_arr[0] = 100

print("arr:", arr)
print("new_arr:", new_arr)

arr: [10 20 30]
new_arr: [100  20  30]


In [7]:
# 6 view creates a view that normally shares the same underlying data.
arr = np.array([10, 20, 30])
new_arr = arr.view()

new_arr[0] = 100

print("arr:", arr)
print("new_arr:", new_arr)

arr: [100  20  30]
new_arr: [100  20  30]


In [8]:
# 7 Memory Sharing 
# Memory sharing means two array objects use the same underlying data.
arr = np.array([10,20,30])

view_arr = arr.view()
copy_arr = arr.copy()

print("view:", np.shares_memory(arr, view_arr))
print("Copy:", np.shares_memory(arr, copy_arr))

view: True
Copy: False


In [9]:
# 8 shares Memory
# checks whether two arrays actually share memory.
a= np.array([1,2,3,4])

b = a.view()
c = a.copy()

print("view:",np.shares_memory(a,b))
print("Copy:",np.shares_memory(a,c))

view: True
Copy: False


In [10]:
# 9 may_share_memory checks whether two arrays might share memory.
a = np.array([1, 2, 3, 4, 5])

b = a[1:4]
c = a.copy()

print(np.may_share_memory(a, b))
print(np.may_share_memory(a, c))

True
False


In [11]:
# 10 View vs Copy Direct Comparison
arr = np.array([10,20,30])

view_arr = arr.view()
copy_arr = arr.copy()

view_arr[0] = 100
copy_arr[1] = 200

print("Original:",arr)
print("View:",view_arr)
print("Copy:",copy_arr)

Original: [100  20  30]
View: [100  20  30]
Copy: [ 10 200  30]


In [12]:
# np.array() → creates an array
# arr.view() → creates a view
# arr.copy() → creates an independent copy
# np.shares_memory() → checks actual memory sharing
# np.may_share_memory()→ checks whether memory may be shared

# Most important:
# View → changes can affect the original.
# Copy → changes do not affect the original.