In [1]:
import numpy as np 

In [2]:
# 1. What is Broadcasting
# Broadcasting means NumPy can perform operations between arrays of different shapes.
a = np.array([10,20,30])
b = 5

result = a + b
print(result)

[15 25 35]


In [3]:
# 2  Broadcasting Rules
# NumPy compares array shapes from right to left.
# Two dimensions are compatible when:
# 1. They are equal, OR
# 2. One of them is 1.

a = np.array([[1,2,3],[4,5,6]])
b = np.array([10,20,30])

print(a + b)

[[11 22 33]
 [14 25 36]]


In [4]:
# 3. Scalar Broadcasting
# A scalar is a single number.
# 10 is broadcasting
a = np.array([[1,2],
              [3,4]])

result = a + 10
print(result)

[[11 12]
 [13 14]]


In [5]:
# 4. 1D Broadcasting
# A 1D array can be added to another compatible 1D array.
a = np.array([10,20,30])
b = np.array([1,2,3])
print(a + b)

[11 22 33]


In [6]:
# 5. 2D Broadcasting
# Both arrays have shape (2, 3), so NumPy adds matching elements.
a = np.array([[1,2,3],
              [4,5,6]])

b = np.array([[10,20,30],
              [40,50,60]])

print(a + b)

[[11 22 33]
 [44 55 66]]


In [7]:
# 6. Row Broadcasting
# A row vector has shape (1, 3).
a = np.array([[1,2,3],
              [4,5,6]])
row = np.array([10,20,30])
print( a + row)

[[11 22 33]
 [14 25 36]]


In [8]:
# 7. Column Broadcasting
# A column vector has shape (2, 1).
a = np.array([[1,2,3],
              [4,5,6]])

column = np.array([[10],
                   [20]])

print(a + column)

[[11 12 13]
 [24 25 26]]


In [9]:
# 8. Broadcasting Error
# Broadcasting fails when shapes are incompatible.
a = np.array([[1,2,3],
              [4,5,6]])

b = np.array([10,20])
print(a + b)

ValueError: operands could not be broadcast together with shapes (2,3) (2,) 

In [10]:
# 9. Broadcasting with Arithmetic
# Broadcasting works with +, -, *, and /.
# The 1D array is broadcast across both rows.
a = np.array([[10,20,30],
              [40,50,60]])

b = np.array([1,2,3])

print(a - b)
print(a * b)

[[ 9 18 27]
 [39 48 57]]
[[ 10  40  90]
 [ 40 100 180]]


In [11]:
# 10. Broadcasting with Functions
# NumPy functions can also use broadcasting.
a = np.array([[1,4,9],
              [16,25,36]])

b = np.array([1,2,3])

result = np.sqrt(a) + b
print(result)

[[2. 4. 6.]
 [5. 7. 9.]]
