In [1]:
import numpy as np 

In [2]:
# 1 concatenate Joins arrays along an existing axis. It does not create a new axis
a = np.array([1,2,3])
b = np.array([4,5,6])

print(np.concatenate((a,b)))

[1 2 3 4 5 6]


In [3]:
# 2 stack Joins arrays along a new axis. The input arrays must have the same shape
a = np.array([1,2,3])
b = np.array([4,5,6])

print(np.stack((a,b), axis=1))

[[1 4]
 [2 5]
 [3 6]]


In [4]:
# 3 vstack Stacks arrays vertically, usually increasing the number of rows.
a = np.array([[1,2,],[3,4]])
b = np.array([[5,6,],[7,8]])

print(np.vstack((a,b)))

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [5]:
# 4 hstack Stacks arrays horizontally, usually increasing the number of columns
print(np.hstack((a,b)))

[[1 2 5 6]
 [3 4 7 8]]


In [6]:
# 5 dstack Stacks arrays along the third axis (depth). For 2-D arrays, this creates a 3-D result.
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])

print(np.dstack((a,b)))

[[[1 5]
  [2 6]]

 [[3 7]
  [4 8]]]


In [7]:
# 6 column_stack Stacks 1-D arrays as columns. For 2-D arrays, it behaves like horizontal stacking.
a = np.array([1,2,3])
b = np.array([4,5,6])

print(np.column_stack((a,b)))

[[1 4]
 [2 5]
 [3 6]]


In [8]:
# 7 row_stack Stacks 1-D arrays as rows. It is equivalent to vstack() for this common use.
a = np.array([1,2,3])
b = np.array([4,5,6])

print(np.row_stack((a,b)))

[[1 2 3]
 [4 5 6]]


C:\Users\malav\AppData\Local\Temp\ipykernel_15056\1719636553.py:5: DeprecationWarning: `row_stack` alias is deprecated. Use `np.vstack` directly.
  print(np.row_stack((a,b)))


In [9]:
# concatenate = join existing axis
# stack = create a new axis
# vstack = vertical / rows
# hstack = horizontal / columns
# dstack = depth / 3rd axis
# column_stack = columns
# row_stack = rows