In [1]:
import numpy as np

In [2]:
# 1 Uniform Distribution — np.random.uniform
# Uniform distribution gives random values where every value in the selected range has equal
# chance.
np.random.seed(1)
result = np.random.uniform(10,20,5)
print(result)

[14.17022005 17.20324493 10.00114375 13.02332573 11.46755891]


In [3]:
# 2 Normal Distribution — np.random.normal
# Normal distribution is centered around a mean. The standard deviation controls how spread
# out the values are.
np.random.seed(1)

result = np.random.normal(
    loc=50,
    scale=10,
    size=5
)
print(result)

[66.24345364 43.88243586 44.71828248 39.27031378 58.65407629]


In [4]:
# 3  Binomial Distribution — np.random.binomial
#  Binomial distribution counts the number of successes in a fixed number of independent
# trials.
np.random.seed(1)
result = np.random.binomial(
 n=10,
 p=0.5,
 size=5
)
print(result)

[5 6 0 4 3]


In [5]:
# 4 Poisson Distribution — np.random.poisson
# Poisson distribution models how many times an event happens in a fixed interval when an
# average rate is known.
np.random.seed(1)
result = np.random.poisson(
 lam=4,
 size=5
)
print(result)

[2 2 3 4 4]


In [6]:
# 5 Exponential Distribution — np.random.exponential
#  Exponential distribution is commonly used for waiting time between events.
np.random.seed(1)
result = np.random.exponential(
 scale=2,
 size=5
)
print(result)

[1.07921167e+00 2.54825051e+00 2.28762717e-04 7.20025510e-01
 3.17419190e-01]


In [7]:
# 6 Standard Normal Distribution — np.random.randn
# Standard normal distribution has mean 0 and standard deviation 1.
np.random.seed(1)
result = np.random.randn(5)
print(result)

[ 1.62434536 -0.61175641 -0.52817175 -1.07296862  0.86540763]


In [8]:
# 7 Mean
# Mean is the average of values. Add all values and divide by the number of values.
data = np.array([10, 20, 30, 40, 50])
result = np.mean(data)
print(result)

30.0


In [9]:
# 8 Standard Deviation
# Standard deviation tells us how far values are spread from the mean.
data = np.array([10, 20, 30, 40, 50])
result = np.std(data)
print(result)

14.142135623730951


In [10]:
# 9 Probability
# Probability tells us how likely an event is. It ranges from 0 to 1, or 0% to 100%.
probability = 1 / 6
print(probability)
print(probability * 100)

0.16666666666666666
16.666666666666664


In [11]:
# 10 Random Sampling
# Random sampling means selecting observations randomly from a population.
np.random.seed(1)
data = np.array([10, 20, 30, 40, 50])
sample = np.random.choice(data, size=3, replace=False)
print(sample)

[30 20 50]


In [12]:
# 11 Simulation
# Simulation means using random numbers to imitate a real-world process.
np.random.seed(1)
coin_flips = np.random.choice(
 ["Head", "Tail"],
 size=10
)
print(coin_flips)

['Tail' 'Tail' 'Head' 'Head' 'Tail' 'Tail' 'Tail' 'Tail' 'Tail' 'Head']


In [13]:
# np.random.uniform() — Random values in a range; equal chance across the range.
# np.random.normal() — Random values based on mean and standard deviation.
# np.random.binomial() — Number of successes in fixed trials.
# np.random.poisson() — Number of events for a given average rate.
# np.random.exponential() — Waiting time between events.
# np.random.randn() — Standard normal values: mean 0, standard deviation 1.
# Mean — Average value.
# Standard deviation — Amount of spread around the mean.
# Probability — Chance that an event happens.
# Random sampling — Selecting observations randomly.
# Simulation — Using random data to imitate a real process.