In [1]:
import numpy as np
print(np.__version__)

1.26.4


In [2]:
# 1 unique Removes duplicate values and returns unique values.
arr = np.array([10,20,10,30,20,40])
result = np.unique(arr)
print(result)

[10 20 30 40]


In [3]:
# 2 intersect1d Returns values common to both arrays.
a = np.array([10,20,30,40])
b = np.array([30,40,50,60])
result = np.intersect1d(a,b)
print(result)

[30 40]


In [4]:
# 3 union1d Combines both arrays and removes duplicates.
a = np.array([10,20,30,40])
b = np.array([30,40,50])
result = np.union1d(a,b)
print(result)

[10 20 30 40 50]


In [5]:
# 4 setdiff1 Returns values present in the first array but not the second.
a = np.array([10,20,30,40])
b = np.array([30,40,50])
result = np.setdiff1d(a,b)
print(result)

[10 20]


In [6]:
# 5 setxor1d Returns values present in either array, but not in both
a = np.array([10,20,30])
b = np.array([30,40,50])
result = np.setxor1d(a,b)
print(result)

[10 20 40 50]


In [7]:
# 6 in1d / membership Checks whether every value of the first array exists in the second. np.in1d() is deprecated in newer
# NumPy versions; use np.isin().
import numpy as np
%pip install numpy==1.26.4
a = np.array([10, 20, 30, 40])
b = np.array([20, 40])
result = np.in1d(a, b)
print(result)

Note: you may need to restart the kernel to use updated packages.
[False  True False  True]


In [8]:
# 7 isin Modern membership check. Returns True when a value exists in the second array.
a = np.array([10,20,30,40])
b = np.array([20,40])
result = np.isin(a,b)
print(result)

[False  True False  True]


In [9]:
# Intersection → common values.
# Union → all unique values.
# Difference → values in first array, not second.
# Symmetric difference → values in either array, but not both.
# Membership → checks whether values exist in another array.

In [10]:
# • np.unique() → removes duplicates.
# • np.intersect1d() → common values.
# • np.union1d() → all unique values.
# • np.setdiff1d() → first minus second.
# • np.setxor1d() → values in either, but not both.
# • np.in1d() → older membership function.
# • np.isin() → preferred modern membership function.